---
- name: Update Systems
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - Update

- name: katello-package-upload
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - PackageUpload

- name: katello-tracer-upload
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - Tracer

- name: insights-client
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - Insights

- name: puppet agent -t
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - Puppet

- name: clean logs
  hosts: client1.rring.laptop client2.rring.laptop client3.rring.laptop
  roles:
   - CleanUpLogs
